import type { ImageRef } from '../types'

/**
 * Editorial illustration library. Files live in /public/images and are
 * generated by scripts/gen-images.mjs (duotone SVG compositions on the site
 * palette). No religious imagery: architecture, city, charts, business scenes
 * and speaker portraits only. A CMS will replace these with photography.
 *
 * Every image carries its alt text in Uzbek (the source) plus ru/en versions;
 * the content layer picks the one that matches the language of the text
 * around the image (src/content/index.ts).
 */
export const CREDIT = { uz: 'Illyustratsiya: Muomalat', ru: 'Иллюстрация: Muomalat', en: 'Illustration: Muomalat' } as const

type Alt = { uz: string; ru: string; en: string }

function make(src: string, alt: Alt, width: number, height: number): ImageRef {
  return {
    src: `/images/${src}.svg`,
    alt: alt.uz,
    width,
    height,
    credit: CREDIT.uz,
    translations: {
      ru: { alt: alt.ru, credit: CREDIT.ru },
      en: { alt: alt.en, credit: CREDIT.en },
    },
  }
}

const wide = (src: string, alt: Alt): ImageRef => make(src, alt, 1200, 800)
const square = (src: string, alt: Alt): ImageRef => make(src, alt, 800, 800)

const SPEAKER: Alt = { uz: 'Spiker portreti', ru: 'Портрет спикера', en: 'Speaker portrait' }

export const images = {
  citySkyline: wide('city-skyline', {
    uz: 'Toshkentning ishbilarmonlik markazidagi baland binolar silueti',
    ru: 'Силуэт высотных зданий в деловом центре Ташкента',
    en: 'Silhouette of high-rise buildings in Tashkent’s business district',
  }),
  cityStreet: wide('city-street', {
    uz: 'Ofis binolari va doʻkonlar joylashgan shahar koʻchasi',
    ru: 'Городская улица с офисными зданиями и магазинами',
    en: 'City street lined with office buildings and shops',
  }),
  facadeLattice: wide('facade-lattice', {
    uz: 'Quyoshdan himoya panjarasi bilan qoplangan modernistik bino jabhasi',
    ru: 'Фасад модернистского здания с солнцезащитной решёткой',
    en: 'Modernist building facade behind a sun-shading screen',
  }),
  bankHall: wide('bank-hall', {
    uz: 'Ustunlar va mijozlarga xizmat koʻrsatish oynalari boʻlgan bank zali',
    ru: 'Операционный зал банка с колоннами и окнами обслуживания клиентов',
    en: 'Bank hall with columns and customer service counters',
  }),
  glassTower: wide('glass-tower', {
    uz: 'Shisha jabhali zamonaviy ofis minorasi',
    ru: 'Современная офисная башня со стеклянным фасадом',
    en: 'Modern office tower with a glass facade',
  }),
  chartLine: wide('chart-line', {
    uz: 'Oʻsish tendensiyasini koʻrsatuvchi chiziqli grafik',
    ru: 'Линейный график, показывающий тенденцию роста',
    en: 'Line chart showing an upward trend',
  }),
  chartBars: wide('chart-bars', {
    uz: 'Ustunli diagramma koʻrinishidagi moliyaviy koʻrsatkichlar',
    ru: 'Финансовые показатели в виде столбчатой диаграммы',
    en: 'Financial figures shown as a bar chart',
  }),
  chartCandles: wide('chart-candles', {
    uz: 'Birja kotirovkalarining shamchali grafigi',
    ru: 'Свечной график биржевых котировок',
    en: 'Candlestick chart of market prices',
  }),
  meetingTable: wide('meeting-table', {
    uz: 'Yuqoridan koʻrinish: muzokaralar stoli atrofida hujjatlar va noutbuklar',
    ru: 'Вид сверху: документы и ноутбуки на столе переговоров',
    en: 'Overhead view of documents and laptops on a meeting table',
  }),
  signing: wide('signing', {
    uz: 'Shartnoma imzolanayotgan stol, hujjatlar va qalam',
    ru: 'Подписание договора: стол, документы и ручка',
    en: 'Contract signing: a desk, documents and a pen',
  }),
  workshop: wide('workshop', {
    uz: 'Kichik ishlab chiqarish sexi: dastgohlar va ishchi stollar',
    ru: 'Небольшой производственный цех: станки и верстаки',
    en: 'Small manufacturing workshop with machines and workbenches',
  }),
  agriField: wide('agri-field', {
    uz: 'Yuqoridan koʻrinish: ekin maydonlari va sugʻorish kanallari',
    ru: 'Вид сверху: поля и оросительные каналы',
    en: 'Aerial view of fields and irrigation canals',
  }),
  containers: wide('containers', {
    uz: 'Logistika terminalidagi yuk konteynerlari',
    ru: 'Грузовые контейнеры на логистическом терминале',
    en: 'Shipping containers at a logistics terminal',
  }),
  construction: wide('construction', {
    uz: 'Qurilish maydonidagi minorali kran va karkas bino',
    ru: 'Башенный кран и каркас здания на стройплощадке',
    en: 'Tower crane and a building frame on a construction site',
  }),
  vehicles: wide('vehicles', {
    uz: 'Lizingga beriladigan yuk avtomobillari qatori',
    ru: 'Ряд грузовиков, которые сдаются в лизинг',
    en: 'A row of lorries offered for leasing',
  }),
  globe: wide('globe', {
    uz: 'Meridian va parallellar toʻri tushirilgan globus',
    ru: 'Глобус с сеткой меридианов и параллелей',
    en: 'Globe with a grid of meridians and parallels',
  }),
  gulfSkyline: wide('gulf-skyline', {
    uz: 'Xalqaro moliya markazidagi osmonoʻpar binolar',
    ru: 'Небоскрёбы международного финансового центра',
    en: 'Skyscrapers in an international financial centre',
  }),
  financialDistrict: wide('financial-district', {
    uz: 'Xorijiy moliya tumanining koʻchasi va bank binolari',
    ru: 'Улица и здания банков в зарубежном финансовом районе',
    en: 'A street and bank buildings in a foreign financial district',
  }),
  clubHall: wide('club-hall', {
    uz: 'Klub uchrashuvi uchun tayyorlangan zal: stullar qatori va ekran',
    ru: 'Зал, подготовленный к встрече клуба: ряды стульев и экран',
    en: 'Hall set up for a club meeting, with rows of chairs and a screen',
  }),
  panel: wide('panel', {
    uz: 'Sahnadagi panel muhokamasi: toʻrtta stul va kichik stol',
    ru: 'Панельная дискуссия на сцене: четыре стула и небольшой стол',
    en: 'Panel discussion on stage: four chairs and a small table',
  }),
  portrait01: square('portrait-01', SPEAKER),
  portrait02: square('portrait-02', SPEAKER),
  portrait03: square('portrait-03', SPEAKER),
  portrait04: square('portrait-04', SPEAKER),
  portrait05: square('portrait-05', SPEAKER),
  portrait06: square('portrait-06', SPEAKER),
  portrait07: square('portrait-07', SPEAKER),
  portrait08: square('portrait-08', SPEAKER),
} satisfies Record<string, ImageRef>

export type ImageKey = keyof typeof images

/**
 * Use a library image with an article-specific caption or alt text. An `alt`
 * override without `translations` is taken to be language-neutral (a person's
 * name on a portrait) and is used in every edition.
 */
export function img(key: ImageKey, overrides: Partial<ImageRef> = {}): ImageRef {
  const base = images[key]
  const { alt } = overrides
  const translations =
    overrides.translations ??
    (alt
      ? {
          ru: { alt, credit: base.translations?.ru?.credit },
          en: { alt, credit: base.translations?.en?.credit },
        }
      : base.translations)
  return { ...base, ...overrides, translations }
}
